name: CI/CD Pipeline - tradeport-backend-mssql

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin        

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ../tradeport-backend-mssql/Dockerfile
          push: true
          tags: prabhulalithakrishnan/tradeport-backend-mssql:latest  

  deploy:
    name: Deploy using Docker Compose and Railway
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Deploy with Docker Compose
        run: docker-compose -f ../tradeport-backend-mssql/docker-compose.yml up --build -d
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_SERVER: ${{ secrets.DB_SERVER }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}

      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Authenticate to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway login

      - name: Deploy to Railway
        run: railway up
